services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    #  - /app/node_modules
    environment:
      - MONGODB_URL=mongodb://mongo:27017/ihost
    env_file:
      - .env.development

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
